## 원핫인코딩 직접구현

In [2]:
# 인코딩 대상 단어를 담은 리스트
word_ls=['원숭이','바나나','사과','코끼리']

In [3]:
from collections import defaultdict
import numpy as np

# {단어:인덱스} 사전 구축, 생성된 사전 길이만큼 제한없이 만들어주기 위해 lambda 함수 사용.
word2id_dic = defaultdict(lambda:len(word2id_dic))

In [10]:
for word in word_ls:
    word2id_dic[word]
word2id_dic

defaultdict(<function __main__.<lambda>()>,
            {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})

In [6]:
# 고유단어갯수 : 4개
n_unique_words = len(word2id_dic)
n_unique_words

4

In [8]:
# 원핫 벡터를 만들기 위해 비어있는 벡터 생성
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))  # (4,4)
one_hot_vectors

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# 단어고유 인덱스
for i,word in enumerate(word_ls):
    index = word2id_dic[word]
    one_hot_vectors[i,index] += 1 # 단어 고유 인덱스에 1을 더해줌.
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## sklearn으로 구현

In [12]:
!pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1321 sha256=b6af1c96827b5fe11dd0c9bb793f34d0e690c8ab9efd90c4303aae38e37c0351
  Stored in directory: c:\users\jminw\appdata\local\pip\cache\wheels\46\ef\c3\157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [13]:
# sklearn을 활용한 one-hot-encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 예제 데이터 배열
values = array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [14]:
# 문자열에 숫자를 붙임
label_enc = LabelEncoder()  # 선언
int_enc = label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3], dtype=int64)

In [19]:
# binary encode
onehot_enc = OneHotEncoder(sparse=False)  # 선언
int_enc = int_enc.reshape(len(int_enc), 1) # n:1 matrix로 변환
print(int_enc)
# int_enc 1행을 밑에처럼 4행으로 변환시켜 주는 것

onehot_enc = onehot_enc.fit_transform(int_enc)
onehot_enc

[[2]
 [0]
 [1]
 [3]]


array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])