In [29]:
d = {'height':180, 'weight':78, 'temparature':36, 'eyesight':1}
for i in d:
    if 70<i[1]<100:
        print(i)

TypeError: '<' not supported between instances of 'int' and 'str'

In [30]:
d = {'height':180, 'weight':78, 'temparature':36, 'eyesight':1}
for i in d.items():
    if i[1]==78:
        print('key=', i[0])
        break

key= weight


In [31]:
for i in d.items():
    print( 'i=', i , 'i[0]=', i[0], 'i[1]=', i[1])

i= ('height', 180) i[0]= height i[1]= 180
i= ('weight', 78) i[0]= weight i[1]= 78
i= ('temparature', 36) i[0]= temparature i[1]= 36
i= ('eyesight', 1) i[0]= eyesight i[1]= 1


In [37]:
d = {'1반':[60,80,30], '2반':[78, 54, 98], '3반':[100, 50, 70], '4반':[70, 60, 80]}
d

{'1반': [60, 80, 30],
 '2반': [78, 54, 98],
 '3반': [100, 50, 70],
 '4반': [70, 60, 80]}

In [38]:
for i in d.items():
    print( 'i=', i , 'i[0]=', i[0], 'i[1]=', i[1])

i= ('1반', [60, 80, 30]) i[0]= 1반 i[1]= [60, 80, 30]
i= ('2반', [78, 54, 98]) i[0]= 2반 i[1]= [78, 54, 98]
i= ('3반', [100, 50, 70]) i[0]= 3반 i[1]= [100, 50, 70]
i= ('4반', [70, 60, 80]) i[0]= 4반 i[1]= [70, 60, 80]


In [41]:
for i in d.items():
    print( 'i=', i , 'i[0]=', i[0], 'i[1]=', i[1])
    print ('국어=',i[1][0], '영어=',i[1][1], '수학=',i[1][2])

i= ('1반', [60, 80, 30]) i[0]= 1반 i[1]= [60, 80, 30]
국어= 60 영어= 80 수학= 30
i= ('2반', [78, 54, 98]) i[0]= 2반 i[1]= [78, 54, 98]
국어= 78 영어= 54 수학= 98
i= ('3반', [100, 50, 70]) i[0]= 3반 i[1]= [100, 50, 70]
국어= 100 영어= 50 수학= 70
i= ('4반', [70, 60, 80]) i[0]= 4반 i[1]= [70, 60, 80]
국어= 70 영어= 60 수학= 80


In [43]:
for i in d.items():
    print( 'i=', i , 'i[0]=', i[0], 'i[1]=', i[1])
    print ('국어=',i[1][0], '영어=',i[1][1], '수학=',i[1][2])
    if i[1][1] == 50:
        print('key=', i[0])
        break

i= ('1반', [60, 80, 30]) i[0]= 1반 i[1]= [60, 80, 30]
국어= 60 영어= 80 수학= 30
i= ('2반', [78, 54, 98]) i[0]= 2반 i[1]= [78, 54, 98]
국어= 78 영어= 54 수학= 98
i= ('3반', [100, 50, 70]) i[0]= 3반 i[1]= [100, 50, 70]
국어= 100 영어= 50 수학= 70
key= 3반


In [81]:
def sum_n(n):
    total=0
    count=1
    for i in range(1,n+1):
        total=total+count
        count=count+1
        if count==n+1:
            break
    return total

In [82]:
print(sum_n(10))

55


In [83]:
print(sum_n(25))

325


In [62]:
def sum_n(n):
    sum=0
    for i in range(1,n+1):
        sum=sum+i
        print('i=', i, 'sum=', sum)
    return sum

In [63]:
print(sum_n(10))
print(sum_n(25))

i= 1 sum= 1
i= 2 sum= 3
i= 3 sum= 6
i= 4 sum= 10
i= 5 sum= 15
i= 6 sum= 21
i= 7 sum= 28
i= 8 sum= 36
i= 9 sum= 45
i= 10 sum= 55
55
i= 1 sum= 1
i= 2 sum= 3
i= 3 sum= 6
i= 4 sum= 10
i= 5 sum= 15
i= 6 sum= 21
i= 7 sum= 28
i= 8 sum= 36
i= 9 sum= 45
i= 10 sum= 55
i= 11 sum= 66
i= 12 sum= 78
i= 13 sum= 91
i= 14 sum= 105
i= 15 sum= 120
i= 16 sum= 136
i= 17 sum= 153
i= 18 sum= 171
i= 19 sum= 190
i= 20 sum= 210
i= 21 sum= 231
i= 22 sum= 253
i= 23 sum= 276
i= 24 sum= 300
i= 25 sum= 325
325


In [84]:
def sum_n(n):
    return n*(n+1)/2

In [85]:
print(sum_n(10))
print(sum_n(25))

55.0
325.0


In [1]:
res= list(range(1,10001))
res1= str(res)
res1.count('8')

4000

In [3]:
print(str(list(range(1, 10001))).count('8'))

4000


In [118]:
name = ['홍길동', '이순신', '이성계']
name

['홍길동', '이순신', '이성계']

In [119]:
res = ''.join(name) ; res

'홍길동이순신이성계'

In [120]:
res.count('이')

2

In [6]:
import pandas as pd
from pandas import Series, DataFrame

In [21]:
ef = {'country': ['벨기에','인도','브라질'],
     'capital': ['브뤼셀','뉴델리','브라질리아'],
     'population': ['1천만명','13억명','2억명']}
af= DataFrame(ef)
af

country capital population
0     벨기에     브뤼셀       1천만명
1      인도     뉴델리       13억명
2     브라질   브라질리아        2억명

In [22]:
af.iloc[1,2]

'13억명'

In [23]:
af.iloc[1,2] = '14억명' ; af

country capital population
0     벨기에     브뤼셀       1천만명
1      인도     뉴델리       14억명
2     브라질   브라질리아        2억명

In [24]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [27]:
np.empty((4,4))

array([[6.23042070e-307, 7.56587584e-307, 1.37961302e-306,
        1.05699242e-307],
       [8.01097889e-307, 1.11261162e-306, 1.69119330e-306,
        6.89805151e-307],
       [7.56592338e-307, 6.89807188e-307, 1.11261502e-306,
        1.24610723e-306],
       [1.42418172e-306, 1.37961641e-306, 1.33508760e-307,
        8.45610231e-307]])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr.shape

(2, 3)

In [32]:
arr.ndim

2

In [33]:
arr.dtype

dtype('int32')

In [34]:
arr_int=np.array([1,2,3,4])
arr_int.dtype

dtype('int32')

In [35]:
arr_float = arr_int.astype(np.float64)
arr_float.dtype

dtype('float64')

In [36]:
arr_str= np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [37]:
arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [43]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [50]:
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [51]:
arr2 = np.array([[5,6],[7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [52]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [53]:
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [54]:
arr1*arr2

array([[ 5, 12],
       [21, 32]])

In [55]:
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [56]:
arr1.dot(arr2)

array([[19, 22],
       [43, 50]])

In [57]:
np.dot(arr1, arr2)

array([[19, 22],
       [43, 50]])

In [62]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr_1= arr[:2,1:3]

In [64]:
arr_1

array([[2, 3],
       [5, 6]])

In [65]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr[0,2]

3

In [67]:
arr[[0,1,2],[2,0,1]]

array([3, 4, 8])

In [69]:
arr = np.array([[1,2,3],[4,5,6]]) 
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
idx = arr > 3   ######## arr 에서 3 보다 큰 값을 찾아서 같은 Shape 의 True or False 값을 가진 배열로 생성
idx

array([[False, False, False],
       [ True,  True,  True]])

In [71]:
print(arr[idx])   # 만들어 놓은 idx 를 통해 조건에 맞는 배열 구성

[4 5 6]


In [73]:
import numpy as np
redwine = np.loadtxt(fname='C:/jms/winequality-red.csv', delimiter=';', skiprows=1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [75]:
redwine.shape

(1599, 12)

In [76]:
redwine.dtype

dtype('float64')

In [77]:
redwine.ndim

2

In [78]:
## redwine 데이터셋의 합 (sum)
print(redwine.sum()) 

152084.78194


In [79]:
## redwine 데이터셋의 평균 (mean)
print(redwine.mean())

7.926036165311652


In [80]:
print(redwine.mean(axis=0))  
##redwine.mean(axis=0) : redwine 데이터 셋의 열별(axis=0은 열을 뜻한다) 평균, 이를 통해 각 변수별 평균을 알 수 있다.

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [81]:
print(redwine.mean(axis=1)) 

[ 6.21198333 10.25456667  8.30825    ...  8.37347833  8.76795583
  7.7077075 ]


In [82]:
print(redwine[:,0].mean()) # redwine[:,0].mean(): redwine데이터셋의첫번째열(0번째열)의모든값들의평균을뜻한다.즉, fixed acidity의평균만알수있다.

8.31963727329581


In [83]:
print(redwine.max(axis=0))

[ 15.9       1.58      1.       15.5       0.611    72.      289.
   1.00369   4.01      2.       14.9       8.     ]


In [84]:
print(redwine.min(axis=0))

[4.6     0.12    0.      0.9     0.012   1.      6.      0.99007 2.74
 0.33    8.4     3.     ]


In [85]:
import numpy as np
a= np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
a.shape

(3, 5)

In [87]:
a.reshape(-1,3)     ##### 3열로 넘파이가 임의로 만들어라 ;-1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [88]:
a.reshape(3,-1)  ##### 3행으로 넘파이 네가 알아서 만들어라  =-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [89]:
a.ndim

2

In [90]:
a.dtype.name

'int32'

In [91]:
a.itemsize

4

In [92]:
a.size

15

In [93]:
type(a)

numpy.ndarray

In [94]:
b = np.array([6,7,8])
b

array([6, 7, 8])

In [95]:
type(b)

numpy.ndarray

In [96]:
2*2*2*2

16

In [98]:
a = np.arange(24) ; a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [100]:
b=a.reshape(2,3,2,2); b  #### 뒤에서부터, 2*2가 3개고 그 3개가 2개의 덩어리..

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [101]:
b.ndim

4

In [103]:
a = np.array((2,3,4)) ;a

array([2, 3, 4])

In [104]:
a = (3, 4, 5)
np.array(a)

array([3, 4, 5])

In [105]:
b = np.array([(1.5,2,3), (4,5,6)]) ; b   #####실수면 실수, 정수면 정수로 알아서 통일하여 처리함.

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [106]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [109]:
np.ones_like((2,3,4), dtype=np.int16)

array([1, 1, 1], dtype=int16)

In [108]:
np.empty( (2,3) )                                 # uninitialized

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [110]:
np.arange( 10, 30, 5 )     #### star, end, step  -> 시작, 끝, @씩 건너뛴다.

array([10, 15, 20, 25])

In [111]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [112]:
from numpy import pi     
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2 0부터 2까지 9개 숫자로 나눠라.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [115]:
x = np.linspace( 0, 2*pi, 100 )      ; x
###위에 from numpy import pi가 없으면 여기에 np.pi도 대체가능  # useful to evaluate function at lots of points

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [116]:
f = np.sin(x) ;f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [117]:
a = np.arange(6)                         # 1d array

In [118]:
print(a)

[0 1 2 3 4 5]


In [119]:
b = np.arange(12).reshape(4,3)           # 2d array

In [120]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [121]:
c = np.arange(24).reshape(2,3,4)         # 3d array

In [122]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [123]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [124]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [127]:
from numpy import sys 
np.set_printoptions(threshold=sys.maxsize)       # sys module should be imported

In [129]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 ) ; b

array([0, 1, 2, 3])

In [131]:
 c = a-b ;c

array([20, 29, 38, 47])

In [132]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [133]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [134]:
a<35

array([ True,  True, False, False])

In [135]:
rg = np.random.default_rng(1)     # create instance of default random number generator 제너레이터 생성.

In [143]:
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))  ;b
### 랜덤이라 값이 자꾸 변함. 그래서 값을 변하게 하지 않기위해 np.random.seed()를 앞에 써서 값을 고정시킴.

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [144]:
a *= 3 ; a

array([[3, 3, 3],
       [3, 3, 3]])

In [145]:
b += a ; b    # b에다가 a를 더함.       실수에 정수를 더하는 것은 가능.

array([[3.32973172, 3.7884287 , 3.30319483],
       [3.45349789, 3.1340417 , 3.40311299]])

In [146]:
a += b        ## 정수값에 실수 더하는 것은 인정하지 않음.

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [142]:
np.random.seed(0)            # np.random.seed(0)
b = np.random.rand((2,3))  ; b

TypeError: 'tuple' object cannot be interpreted as an integer

In [147]:
a = rg.random((2,3)) ;a

array([[0.20345524, 0.26231334, 0.75036467],
       [0.28040876, 0.48519097, 0.9807372 ]])

In [148]:
a.sum()

2.962470185966965

In [149]:
a.min()

0.20345524067614962

In [150]:
a.max()    ###  몇번째가 제일 크다. 정할 수 있음. 

0.9807371998012386

In [151]:
b = np.arange(12).reshape(3,4) ; b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [153]:
b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [154]:
b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

In [157]:
a = np.arange(24).reshape(2,3,4) ; a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [161]:
a.sum(axis=0)    ## 각 분단 행끼리 더함  0+12, 1+13,2+14,***

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [162]:
a.sum(axis=1)  ### 열별로 다 더해서 하나가 나오는.. 0+4+8=12, 1+5+9, 2+6+10, 3+7+11, ***

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [163]:
a.sum(axis=2)   #### 행별로 다 더해서 나온다. 0+1+2+3, 4+5+6+7, 8+9+10+11, ****

array([[ 6, 22, 38],
       [54, 70, 86]])

In [164]:
a = np.arange(6).reshape(2,3) + 10 ; a

array([[10, 11, 12],
       [13, 14, 15]])

In [165]:
np.argmax(a)     #### 1차원일때 제일 큰 index를 알려줌

5

In [166]:
np.argmax(a, axis=0)    ### 열로 봤을때, 10보다 13이 더 크다 10=[0], 13=[1], 이런식으로 큰 수의 위치를 알려줌

array([1, 1, 1], dtype=int64)

In [167]:
np.argmax(a, axis=1)  ### 행으로 봤을때, 10보다 12 더 크다 10=[0], 12=[2], 이런식으로 큰 수의 위치를 알려줌

array([2, 2], dtype=int64)

In [168]:
a = np.arange(10)**3  ; a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [169]:
a[2]

8

In [170]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [171]:
a[:6:2] = 1000 ; a 
# equivalent to a[0:6:2] = 1000;
## 0에서 6까지 2간격으로 1000을 넣어라
# from start to position 6, exclusive, set every 2nd element to 1000

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [172]:
a[ : :-1]  ## 거꾸로 보여달라

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [174]:
for i in a:
    print('i=', i, i**(1/3.))  ### 1/3 삼분의일 제곱

i= 1000 9.999999999999998
i= 1 1.0
i= 1000 9.999999999999998
i= 27 3.0
i= 1000 9.999999999999998
i= 125 5.0
i= 216 5.999999999999999
i= 343 6.999999999999999
i= 512 7.999999999999999
i= 729 8.999999999999998


In [175]:
def f(x,y):
    return 10*x+y

In [176]:
b = np.fromfunction(f,(5,4),dtype=int) ;b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [177]:
b[2,3]

23

In [178]:
b[0:5, 1]    # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [179]:
b[ : ,1]    # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [180]:
b[1:3, : ]   # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [181]:
b[-1]   # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

In [183]:
b[3,2] 

32

In [184]:
c = np.array( [[[  0,  1,  2], [ 10, 12, 13]], [[100,101,102], [110,112,113]]]) ;c
# a 3D array (two stacked 2D arrays)

array([[[  0,   1,   2],
        [ 10,  12,  13]],

       [[100, 101, 102],
        [110, 112, 113]]])

In [185]:
c.shape

(2, 2, 3)

In [186]:
c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [187]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

In [188]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [189]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [192]:
a = np.array(10*rg.random((3,4))) ;a

array([[0.39592877, 5.28589263, 4.59335883, 0.62349579],
       [6.41328169, 8.52632838, 5.92941018, 2.60097448],
       [8.39881521, 5.09495882, 5.10888884, 7.53030208]])

In [193]:
a.shape

(3, 4)

In [200]:
np.floor(a)    #### 소수점 버리기

array([[0., 5., 4., 0.],
       [6., 8., 5., 2.],
       [8., 5., 5., 7.]])

In [204]:
a = np.floor(10*rg.random((3,4)))

In [205]:
a.ravel()  # returns the array, flattened

array([1., 8., 6., 7., 1., 8., 1., 0., 8., 8., 8., 4.])

In [206]:
a.reshape(6,2)  # returns the array with a modified shape

array([[1., 8.],
       [6., 7.],
       [1., 8.],
       [1., 0.],
       [8., 8.],
       [8., 4.]])

In [207]:
a.T  # returns the array, transposed

array([[1., 1., 8.],
       [8., 8., 8.],
       [6., 1., 8.],
       [7., 0., 4.]])

In [208]:
a.T.shape

(4, 3)

In [209]:
a.shape

(3, 4)

In [212]:
a.resize((2,6)) ;a

array([[1., 8., 6., 7., 1., 8.],
       [1., 0., 8., 8., 8., 4.]])

In [213]:
a.reshape(3,-1)

array([[1., 8., 6., 7.],
       [1., 8., 1., 0.],
       [8., 8., 8., 4.]])

In [214]:
a = np.floor(10*rg.random((2,2))) ;a

array([[2., 0.],
       [6., 7.]])

In [215]:
b = np.floor(10*rg.random((2,2))) ;b

array([[8., 2.],
       [2., 6.]])

In [216]:
np.vstack((a,b))    ## 열의 수가 같은 두 개 이상의 배열을 위아래로 연결

array([[2., 0.],
       [6., 7.],
       [8., 2.],
       [2., 6.]])

In [217]:
np.hstack((a,b))   ### 옆으로 배열

array([[2., 0., 8., 2.],
       [6., 7., 2., 6.]])

In [218]:
from numpy import newaxis
np.column_stack((a,b))# with 2D arrays

array([[2., 0., 8., 2.],
       [6., 7., 2., 6.]])

In [219]:
a = np.array([4.,2.])

In [220]:
b = np.array([3.,8.])

In [221]:
np.column_stack((a,b))  # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [222]:
np.hstack((a,b))# the result is different

array([4., 2., 3., 8.])

In [223]:
a[:,newaxis] # view `a` as a 2D column vector

array([[4.],
       [2.]])

In [224]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [225]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])